### ISSUE TITLE
AUTH_USER_MODEL refers to model 'users.Users' that has not been installed

### ISSUE THREAD

**Issue by c0desway** [kwatog/jumuk#1]
How can I solve this error?
There is no 'Users' in 'users' module.

**Comment by kwatog** [comment]
at what point do you encounter this? when you call the runserver?

In views.py, the User model is already explicitly imported.
`
from .models import User
`

In authentication.py, it is accessed via get_user_model()

If you try to clone the repository now (including the sqlite), you only need to define the environment variable below, install requirements.txt via pip, and then runserver.

`
export DJANGO_FIREBASE_CRED=/home/kwatog/jumuk/projectlibre-firebase-adminsdk-ra255-caa1532e11.json
`
